eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://clouddemo:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: springcloud-zuul
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    springcloud-spider:
      path: /spider/**
      serviceId: springcloud-spider
    springcloud-fang:
      path: /fang/**
      serviceId: springcloud-fang